config/routes.rb
Rails.application.routes.draw do

 resources :henry

end

app/models/henry.rb
class Henry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/henry_controller.rb
class HenryController < ApplicationController
    def new
    end

    def create
        @henry = Henry.new(article_params)
        @henry.save
        redirect_to @henry
    end

    def index
        @all = Henry.all
    end


    def show
      @henry =  Henry.find(params[:id])
    end

    def edit
         @henry =  Henry.find(params[:id])
     end
     def update
        @henry = Henry.find(params[:id])

    if @henry.update(article_params)
        redirect_to @henry
    else
        render 'edit'
    end
     end

    private
    def article_params
        params.require(:henry).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/henrys_helper.rb
module HenrysHelper
end

app/views/henry/edit.html.erb
<%= form_for :henry, url:henry_path(@henry) , method: :patch do |f| %>
  <p>
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/henry/index.html.erb
<h1>Listing henrys</h1>

<table>
  <tr>
    <th>Nome</th>
  </tr>

  <% @all.each do |henry| %>
    <tr>
      <td><%= henry.nome %></td>
      <td><%= link_to 'edit', edit_henry_path(henry) %></td>
  <% end %>
</table>

app/views/henry/new.html.erb
<%= form_for :henry, url:henry_index_path do |f| %>
  <p>
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/henry/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @henry.nome %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agavee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>